public with sharing class CtrlTWDProjectCharter 
{
    //---------------------------Page 1 -----------------------------
	public string TWD_Page1_10 { get; set; }
    public string TWD_Page1_20 { get; set; }
    public string TWD_Page1_30 { get; set; }
    public string TWD_Page1_40 { get; set; }
    //---------------------------Page 2 -----------------------------
    public string TWD_Page2_10 { get; set; }
    public string TWD_Page2_20 { get; set; }
    public string TWD_Page2_30 { get; set; }
    public boolean TWD_Page2_40 { get; set; }
    public boolean TWD_Page2_50 { get; set; }
    public boolean TWD_Page2_60 { get; set; }
    public boolean TWD_Page2_70 { get; set; }
    public string TWD_Page2_80 { get; set; }
    public string TWD_Page2_90 { get; set; }
    public string TWD_Page2_100 { get; set; }
    public boolean TWD_Page2_110 { get; set; }
    public string TWD_Page2_120 { get; set; }
    public boolean TWD_Page2_130 { get; set; }
    public string TWD_Page2_140 { get; set; }
    public boolean TWD_Page2_150 { get; set; }
    public string TWD_Page2_160 { get; set; }
    public boolean TWD_Page2_170 { get; set; }
    public string TWD_Page2_180 { get; set; }
    public boolean TWD_Page2_190 { get; set; }
    public string TWD_Page2_200 { get; set; }
    public boolean TWD_Page2_210 { get; set; }
    public string TWD_Page2_220 { get; set; }
    public boolean TWD_Page2_230 { get; set; }
    public string TWD_Page2_240 { get; set; }
    public boolean TWD_Page2_250 { get; set; }
    public string TWD_Page2_260 { get; set; }
    public boolean TWD_Page2_270 { get; set; }
    public string TWD_Page2_280 { get; set; }
    public boolean TWD_Page2_290 { get; set; }
    public string TWD_Page2_300 { get; set; }
    public boolean TWD_Page2_310 { get; set; }
    public string TWD_Page2_320 { get; set; }
    public boolean TWD_Page2_330 { get; set; }
    public string TWD_Page2_340 { get; set; }
    public boolean TWD_Page2_350 { get; set; }
    public string TWD_Page2_360 { get; set; }
    public boolean TWD_Page2_370 { get; set; }
    public string TWD_Page2_380 { get; set; }
    public string TWD_Page2_390 { get; set; }
    public string TWD_Page2_400 { get; set; }
    //---------------------------Page 3 -----------------------------
    public boolean TWD_Page3_10 { get; set; }
    public boolean TWD_Page3_20 { get; set; }
    public string TWD_Page3_30 { get; set; }
    public string TWD_Page3_40 { get; set; }
    public boolean TWD_Page3_50 { get; set; }
    public boolean TWD_Page3_60 { get; set; }
    public boolean TWD_Page3_70 { get; set; }
    public boolean TWD_Page3_80 { get; set; }
    public boolean TWD_Page3_90 { get; set; }
    public boolean TWD_Page3_100 { get; set; }
    public boolean TWD_Page3_110 { get; set; }
    public string TWD_Page3_111 { get; set; }
    public boolean TWD_Page3_120 { get; set; }
    public boolean TWD_Page3_130 { get; set; }
    public boolean TWD_Page3_140 { get; set; }
    public boolean TWD_Page3_150 { get; set; }
    public boolean TWD_Page3_160 { get; set; }
    public string TWD_Page3_170 { get; set; }
    public boolean TWD_Page3_180 { get; set; }
    public boolean TWD_Page3_190 { get; set; }
    public boolean TWD_Page3_200 { get; set; }
    public boolean TWD_Page3_210 { get; set; }
    public boolean TWD_Page3_220 { get; set; }
    public boolean TWD_Page3_230 { get; set; }
    public boolean TWD_Page3_240 { get; set; }
    public boolean TWD_Page3_250 { get; set; }
    public boolean TWD_Page3_260 { get; set; }
    public boolean TWD_Page3_270 { get; set; }
    public boolean TWD_Page3_280 { get; set; }
    public boolean TWD_Page3_290 { get; set; }
    public boolean TWD_Page3_300 { get; set; }
    public boolean TWD_Page3_310 { get; set; }
    public boolean TWD_Page3_320 { get; set; }
    public string TWD_Page3_330 { get; set; }
    public boolean TWD_Page3_340 { get; set; }
    public string TWD_Page3_350 { get; set; }
    public boolean TWD_Page3_360 { get; set; }
    public string TWD_Page3_370 { get; set; }
    public boolean TWD_Page3_380 { get; set; }
    public string TWD_Page3_390 { get; set; }
    public string TWD_Page3_400 { get; set; }
    //---------------------------Page 4 -----------------------------
    public boolean TWD_Page4_10 { get; set; }
    public string TWD_Page4_20 { get; set; }
    public boolean TWD_Page4_30 { get; set; }
    public boolean TWD_Page4_40 { get; set; }
    public boolean TWD_Page4_50 { get; set; }
    public string TWD_Page4_60 { get; set; }
    public boolean TWD_Page4_70 { get; set; }
    public boolean TWD_Page4_80 { get; set; }
    public boolean TWD_Page4_90 { get; set; }
    public string TWD_Page4_100 { get; set; }
    public boolean TWD_Page4_110 { get; set; }
    public string TWD_Page4_120 { get; set; }
    public string TWD_Page4_130 { get; set; }
    public string TWD_Page4_140 { get; set; }
    public string TWD_Page4_150 { get; set; }
    public string TWD_Page4_160 { get; set; }
    public string TWD_Page4_170 { get; set; }
    public string TWD_Page4_180 { get; set; }
    public string TWD_Page4_190 { get; set; }
    public string TWD_Page4_200 { get; set; }
    //---------------------------Page 5 -----------------------------
    public string TWD_Page5_10 { get; set; }
    public string TWD_Page5_20 { get; set; }
    public string TWD_Page5_30 { get; set; }
    public string TWD_Page5_40 { get; set; }
    public string TWD_Page5_50 { get; set; }
    public string TWD_Page5_60 { get; set; }
    public string TWD_Page5_70 { get; set; }
    public string TWD_Page5_80 { get; set; }
    public string TWD_Page5_90 { get; set; }
    public string TWD_Page5_100 { get; set; }
    public string TWD_Page5_110 { get; set; }
    public string TWD_Page5_120 { get; set; }
    public string TWD_Page5_130 { get; set; }
    public string TWD_Page5_140 { get; set; }
    public string TWD_Page5_150 { get; set; }
    public string TWD_Page5_160 { get; set; }
    public string TWD_Page5_170 { get; set; }
    //---------------------------Page 6 -----------------------------
    public string TWD_Page6_10 { get; set; }
    public string TWD_Page6_20 { get; set; }
    public string TWD_Page6_30 { get; set; }
    public string TWD_Page6_40 { get; set; }
    public string TWD_Page6_50 { get; set; }
    public string TWD_Page6_60 { get; set; }
    public string TWD_Page6_70 { get; set; }
    public string TWD_Page6_80 { get; set; }
    public string TWD_Page6_90 { get; set; }
    public string TWD_Page6_100 { get; set; }
    public string TWD_Page6_110 { get; set; }
    public string TWD_Page6_120 { get; set; }
    public string TWD_Page6_130 { get; set; }
    public string TWD_Page6_140 { get; set; }
    public string TWD_Page6_150 { get; set; }
    public string TWD_Page6_160 { get; set; }
    public string TWD_Page6_170 { get; set; }
    public string TWD_Page6_180 { get; set; }
    public string TWD_Page6_190 { get; set; }
    public string TWD_Page6_200 { get; set; }    
    //---------------------------Page 8 -----------------------------
    public string TWD_Page8_10 { get; set; }
    public string TWD_Page8_20 { get; set; }
    public string TWD_Page8_30 { get; set; }
    public string TWD_Page8_40 { get; set; }
    public boolean TWD_Page8_50 { get; set; }
    public boolean TWD_Page8_60 { get; set; }
    public boolean TWD_Page8_70 { get; set; }
    public boolean TWD_Page8_80 { get; set; }
    public boolean TWD_Page8_90 { get; set; }
    public string TWD_Page8_100 { get; set; }
    public string TWD_Page8_110 { get; set; }
    
    private Opportunity opp { get; set; }
    private Quote quote { get; set; }
    
    public CtrlTWDProjectCharter(ApexPages.StandardController stdController)
    {
        this(stdController.getId());
    }
    public CtrlTWDProjectCharter(Id quoteId)
    {
        InitQuote(quoteId);
        InitOpp(this.quote.OpportunityId);
        TWD_Page1_10 =  this.opp.CreatedDate.format('MM/dd/yyyy'); 
        TWD_Page1_20 =  this.opp.Owner.Name;
        TWD_Page1_30 =  this.opp.Name;
        TWD_Page1_40 =  this.opp.TWD_old_SF_Opportunity_ID__c;
        
        TWD_Page2_10 =  this.opp.Account.ESB_Company_Type__c;
        TWD_Page2_20 =  this.quote.Contact.Name;
        TWD_Page2_30 =  this.opp.Name;
        if(this.opp.Opportunity_Subtype__c == 'Pilot')
        {
            TWD_Page2_40 = true;
        }
        else if(this.opp.Opportunity_Subtype__c == 'Rollout')
        {
            TWD_Page2_50 = true;
        }
        else if(this.opp.Opportunity_Subtype__c == 'Change Request')
        {
            TWD_Page2_60 = true;
        }
        else if(this.opp.Opportunity_Subtype__c == 'Project extension')
        {
            TWD_Page2_70 = true;
        }
        TWD_Page2_80 =  'Empty TWD_Page2_80';
        TWD_Page2_90 =  this.opp.Deal_Specification__c;
        TWD_Page2_100 = this.opp.Additional_Rem_PD__c;
        TWD_Page2_120= 'Empty TWD_Page2_120';
        TWD_Page2_140= 'Empty TWD_Page2_140';
        TWD_Page2_160= 'Empty TWD_Page2_160';
        TWD_Page2_180= 'Empty TWD_Page2_180';
        TWD_Page2_200= 'Empty TWD_Page2_200';
        TWD_Page2_220= 'Empty TWD_Page2_220';
        TWD_Page2_240= 'Empty TWD_Page2_240';
        TWD_Page2_260= 'Empty TWD_Page2_260';
        TWD_Page2_280= 'Empty TWD_Page2_280';
        TWD_Page2_300= 'Empty TWD_Page2_300';
        TWD_Page2_320= 'Empty TWD_Page2_320';
        TWD_Page2_340= 'Empty TWD_Page2_340';
        TWD_Page2_360= 'Empty TWD_Page2_360';
        TWD_Page2_380= 'Empty TWD_Page2_380';
        TWD_Page2_390= 'Empty TWD_Page2_390';
        TWD_Page2_400= 'Empty TWD_Page2_400';
        
        TWD_Page3_10 = this.quote.Web_based__c;
        if(this.quote.Specify_types__c != null)
        {
            TWD_Page3_20 = true;
        }
        TWD_Page3_30 = String.valueOf(this.quote.different_IT_systems__c);
        TWD_Page3_40 = this.quote.Specify_types__c;
        TWD_Page3_111= 'Empty TWD_Page3_111';
        TWD_Page3_170= 'Empty TWD_Page3_170';
        TWD_Page3_330= 'Empty TWD_Page3_330';
        TWD_Page3_350= 'Empty TWD_Page3_350';
        TWD_Page3_370= 'Empty TWD_Page3_370';
        TWD_Page3_390= 'Empty TWD_Page3_390';
        TWD_Page3_400= 'Empty TWD_Page3_400';
        
        TWD_Page4_20= 'Empty TWD_Page4_20';
        TWD_Page4_60= 'Empty TWD_Page4_60';
        TWD_Page4_100= 'Empty TWD_Page4_100';
        TWD_Page4_120= 'Empty TWD_Page4_120';
        TWD_Page4_130= 'Empty TWD_Page4_130';
        TWD_Page4_140= 'Empty TWD_Page4_140';
        TWD_Page4_150= 'Empty TWD_Page4_150';
        TWD_Page4_160= 'Empty TWD_Page4_160';
        TWD_Page4_170= 'Empty TWD_Page4_170';
        TWD_Page4_180= 'Empty TWD_Page4_180';
        TWD_Page4_190= 'Empty TWD_Page4_190';
        TWD_Page4_200= 'Empty TWD_Page4_200';
        
        TWD_Page5_10= 'Empty TWD_Page5_10';
        TWD_Page5_20= 'Empty TWD_Page5_20';
        TWD_Page5_30= 'Empty TWD_Page5_30';
        TWD_Page5_40= 'Empty TWD_Page5_40';
        TWD_Page5_50= 'Empty TWD_Page5_50';
        TWD_Page5_60= 'Empty TWD_Page5_60';
        TWD_Page5_70= 'Empty TWD_Page5_70';
        TWD_Page5_80= 'Empty TWD_Page5_80';
        TWD_Page5_90= 'Empty TWD_Page5_90';
        TWD_Page5_100= 'Empty TWD_Page5_100';
        TWD_Page5_110= 'Empty TWD_Page5_110';
        TWD_Page5_120= 'Empty TWD_Page5_120';
        TWD_Page5_130= 'Empty TWD_Page5_130';
        TWD_Page5_140= 'Empty TWD_Page5_140';
        TWD_Page5_150= 'Empty TWD_Page5_150';
        TWD_Page5_160= 'Empty TWD_Page5_160';
        TWD_Page5_170= 'Empty TWD_Page5_170';
        
        TWD_Page6_10= 'Empty TWD_Page6_10';
        TWD_Page6_20= 'Empty TWD_Page6_20';
        TWD_Page6_30= 'Empty TWD_Page6_30';
        TWD_Page6_40= 'Empty TWD_Page6_40';
        TWD_Page6_50= 'Empty TWD_Page6_50';
        TWD_Page6_60= 'Empty TWD_Page6_60';
        TWD_Page6_70= 'Empty TWD_Page6_70';
        TWD_Page6_80= 'Empty TWD_Page6_80';
        TWD_Page6_90= 'Empty TWD_Page6_90';
        TWD_Page6_100= 'Empty TWD_Page6_100';
        TWD_Page6_110= 'Empty TWD_Page6_110';
        TWD_Page6_120= 'Empty TWD_Page6_120';
        TWD_Page6_130= 'Empty TWD_Page6_130';
        TWD_Page6_140= 'Empty TWD_Page6_140';
        TWD_Page6_150= 'Empty TWD_Page6_150';
        TWD_Page6_160= 'Empty TWD_Page6_160';
        TWD_Page6_170= 'Empty TWD_Page6_170';
        TWD_Page6_180= 'Empty TWD_Page6_180';
        TWD_Page6_190= 'Empty TWD_Page6_190';
        TWD_Page6_200= 'Empty TWD_Page6_200';    
        
        TWD_Page8_10= 'Empty TWD_Page8_10';
        TWD_Page8_20= 'Empty TWD_Page8_70';
        TWD_Page8_30= 'Empty TWD_Page8_80';
        TWD_Page8_40= 'Empty TWD_Page8_90';
        TWD_Page8_100= 'Empty TWD_Page8_100';
        TWD_Page8_110= 'Empty TWD_Page8_110';
    }
    
    private void InitOpp(Id oppId)
    {
        this.opp = [Select CreatedDate, Owner.Name, Name, Account.ESB_Company_Type__c,TWD_old_SF_Opportunity_ID__c, 
                    Additional_Rem_PD__c, Deal_Specification__c, Opportunity_Subtype__c From Opportunity Where Id =: oppId];
    }
    
    private void InitQuote(Id quoteId)
    {
        this.quote = [Select Id, OpportunityId,	Web_based__c,Specify_types__c,different_IT_systems__c, Contact.Name From Quote Where Id =: quoteId];
    }
}